export const ERRORS_ENUM = {
  "CART NOT FOUND": "CART NOT FOUND",
  "INVALID CART PROPERTY": "INVALID CART PROPERTY",
  "PRODUCT ALREADY IS IN CART": "PRODUCT ALREADY IS IN CART",
  "CARTS ARE EMPTY": "CARTS ARE EMPTY",
  "PRODUCT NOT FOUND": "PRODUCT NOT FOUND",
  "INVALID PRODUCT PROPERTY": "INVALID PRODUCT PROPERTY",
};
